server:
  port: 7081

spring:
  application:
    name: task-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  liquibase:
    change-log: /rootChangeLog.xml