server:
  port: 7081

spring:
  application:
    name: task-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: /rootChangeLog.xml
  data:
    rest:
      base-path: /datarest

commons:
  rest-exception-handler:
    enabled: true
  loggable-aop:
    enabled: true

logging.level:
  ru.diasoft.spring.commonsspringbootauthoconfigure.aop: DEBUG
  org.hibernate.type: TRACE
